### ISSUE TITLE
Chart : series name with special characters not escaped

### ISSUE THREAD

**Issue by huandzh** [scanny/python-pptx#128]
Hi,

When wrote a series with the name 'Score<5', I had got the following error trace:

```
Traceback (most recent call last):
  File "test_simple.py", line 22, in <module>
    XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data
  File "C:\Anaconda\lib\site-packages\python_pptx-0.5.2-py2.7.egg\pptx\parts\slide.py", line 203, in add_chart

    rId = self.part.add_chart_part(chart_type, chart_data)
  File "C:\Anaconda\lib\site-packages\python_pptx-0.5.2-py2.7.egg\pptx\parts\slide.py", line 67, in add_chart_
part
    chart_part = ChartPart.new(chart_type, chart_data, self.package)
  File "C:\Anaconda\lib\site-packages\python_pptx-0.5.2-py2.7.egg\pptx\parts\chart.py", line 32, in new
    chart_part = cls.load(partname, content_type, chart_blob, package)
  File "C:\Anaconda\lib\site-packages\python_pptx-0.5.2-py2.7.egg\pptx\opc\package.py", line 328, in load
    element = parse_xml(blob)
  File "C:\Anaconda\lib\site-packages\python_pptx-0.5.2-py2.7.egg\pptx\oxml\__init__.py", line 26, in parse_xm
l
    root_element = etree.fromstring(xml, oxml_parser)
  File "lxml.etree.pyx", line 2993, in lxml.etree.fromstring (src\lxml\lxml.etree.c:62980)
  File "parser.pxi", line 1617, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:92828)
  File "parser.pxi", line 1495, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:91637)
  File "parser.pxi", line 1011, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:88294)
  File "parser.pxi", line 577, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:84019
)
  File "parser.pxi", line 676, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:85122)
  File "parser.pxi", line 616, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:84445)
lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 17, column 30
```

I have found that series name were not escaped (https://github.com/scanny/python-pptx/blob/master/pptx/chart/data.py#L140-L161) and fix it temporally in https://github.com/huandzh/python-pptx/tree/escape_series_name . 

But I am not sure whether there are other values not escaped. Maybe a overall escape solution is better.  -0 0

How about you opinion?

**Comment by scanny** [comment]
Fixed in 0.5.8.
