### ISSUE TITLE
Get zipfile error in python 3.4 but not 2.7

### ISSUE THREAD

**Issue by chris1610** [scanny/python-pptx#174]
Trying to open a simple powerpoint template in python 2.7 works fine but trying to do the same in 3.4.3 results in:

zipfile.BadZipFile: File is not a zip file

Code is simply:
prs = Presentation(input)

I've tried several different powerpoints so I don't think it matters which template it is.

**Comment by scanny** [comment]
What operating system?

**Comment by chris1610** [comment]
Ubuntu - using the anaconda distribution.

**Comment by scanny** [comment]
Can you post the entire stack trace?

**Comment by chris1610** [comment]
Traceback (most recent call last):
  File "analyze_ppt.py", line 60, in <module>
    analyze_ppt(args.infile, args.outfile)
  File "analyze_ppt.py", line 33, in analyze_ppt
    prs = Presentation(input)
  File "/home/chris/miniconda3/lib/python3.4/site-packages/pptx/api.py", line 26, in __init__
    self._package = Package.open(pkg_file)
  File "/home/chris/miniconda3/lib/python3.4/site-packages/pptx/package.py", line 44, in open
    return super(Package, cls).open(pkg_file)
  File "/home/chris/miniconda3/lib/python3.4/site-packages/pptx/opc/package.py", line 122, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/home/chris/miniconda3/lib/python3.4/site-packages/pptx/opc/pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/home/chris/miniconda3/lib/python3.4/site-packages/pptx/opc/phys_pkg.py", line 102, in __init__
    self._zipf = ZipFile(pkg_file, 'r')
  File "/home/chris/miniconda3/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/home/chris/miniconda3/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by chris1610** [comment]
I realized the issue actually had to do with the difference in file handling with argparse. I modified that portion of the code and now this works. Sorry for wasting your time!

Thanks again for a great module. It's very helpful.

**Comment by scanny** [comment]
Glad to hear you got it working :)

**Comment by chris1610** [comment]
In case you're interested, here's my blog post - http://pbpython.com/creating-powerpoint.html

Thanks again for this project. It's really very helpful.

**Comment by scanny** [comment]
Really nice post @chris1610, thanks very much for the shout out! :)
