### ISSUE TITLE
Python-Pptx error in QGIS Python console

### ISSUE THREAD

**Issue by BenCEEME** [scanny/python-pptx#204]
Hi,

I am running on the following platform:

- Windows 10 Professional
- OSGeo4W QGIS 2.14 Essen
- Python-Pptx 0.5.8
- Pillow 3.1.1
- XlsxWriter 0.8.4

All modules properly installed without error prompt.

Then I try to import python-pptx and I get immediately a traceback:

import pptx

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "_some_directory_/_some_python_filename_.py", line 28, in <module>
    import pptx
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pptx\__init__.py", line 15, in <module>
    from pptx.api import Presentation  # noqa
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pptx\api.py", line 14, in <module>
    from pptx.package import Package
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pptx\package.py", line 13, in <module>
    from .opc.package import OpcPackage
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pptx\opc\package.py", line 13, in <module>
    from .oxml import CT_Relationships, serialize_part_xml
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pptx\opc\oxml.py", line 12, in <module>
    from lxml import etree
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: Le module spécifié est introuvable.

Any clue as to what is going on and how to fix it?

Thanks!

**Comment by scanny** [comment]
I would focus on the lxml library. You can put together a piece of test code like this:

```python
from lxml import etree
```

If that code doesn't load without error, python-docx won't either.

lxml doesn't build under Windows without Virtual Studio installed and properly configured for compiling the lxml C source. Most folks install it from a binary install on Windows, which for whatever reason needs to be a separate step.

**Comment by BenCEEME** [comment]
Great it works, this is wonderful.

I have documented below the solution in case someone else gets stuck like me.

My config (reminder of above error):

- 64bits machine
- Windows 10
- QGIS OSGeo4W64 2.14.0 (Essen)
- Python-pptx 0.5.8
- Pillow 3.1.1
- XlsxWriter 0.8.4

Note that this implies you have pre-installed pip which is not standard issue for QGis install (the solution is to download and execute the get-pip.py), that you have an internet connection and that your path environment variables are set to QGis properly.

Step by step resolution:

1. Download the relevant lxml for Python 2.7 wheel file according to your machine (x84 or amd64) on: http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
2. Open command line
3. Launch OSGeo4W.bat in the relevant Qgis directory (in my case c:\OSGeo4W64\
4. pip uninstall lxml
5. pip install lxml_whell_file_name.whl (in my case lxml-3.6.0-cp27-cp27m-win_amd64.whl)
6. pip install python-pptx OR pip install python-pptx --upgrade (depending on whether you have alread install python-pptx or not)
7. Tada!

That's all folks and thank you again Scanny!

**Comment by scanny** [comment]
Glad you got it working @BenCEEME :)
