### ISSUE TITLE
AttributeError: 'Layouts' object has no attribute 'iter_cloneable_placeholders'

### ISSUE THREAD

**Issue by prateeksan** [scanny/python-pptx#209]
I am getting this error. Any suggestions as to how I can fix this?

**Comment by scanny** [comment]
You will, of course, need to give us more to go on.

* The minimum code it takes to reproduce the error
* The full stack trace

**Comment by prateeksan** [comment]
Sorry, here is the code the relevant code:

`def presentation(site):
    """Main method"""
    prs = Presentation()
    brand = Brand.create_brand('http://' + site)

    class Layouts(Enum):
        """Presentation Layouts"""
        title = prs.slide_layouts[0]
        bullet = prs.slide_layouts[1]
        title_only = prs.slide_layouts[5]

    slide = prs.slides.add_slide(Layouts.title_only)`

Here is the stack trace:

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/prateeksanyal/Desktop/5Crowd/branding-guidelines/server.py", line 9, in brand_site
    output = presentation(site)
  File "/Users/prateeksanyal/Desktop/5Crowd/branding-guidelines/brand_guideline.py", line 49, in presentation
    slide = prs.slides.add_slide(Layouts.title_only)
  File "/usr/local/lib/python2.7/site-packages/pptx/parts/presentation.py", line 127, in add_slide
    slide = Slide.new(slidelayout, partname, package)
  File "/usr/local/lib/python2.7/site-packages/pptx/parts/slide.py", line 72, in new
    slide.shapes.clone_layout_placeholders(slide_layout)
  File "/usr/local/lib/python2.7/site-packages/pptx/shapes/shapetree.py", line 197, in clone_layout_placeholders
    for placeholder in slide_layout.iter_cloneable_placeholders():
AttributeError: 'Layouts' object has no attribute 'iter_cloneable_placeholders'`

**Comment by prateeksan** [comment]
Update, I got it work. Thanks :)

**Comment by scanny** [comment]
Glad you got it working @prateeksan :)
