### ISSUE TITLE
feature: Connector.line

### ISSUE THREAD

**Issue by richielionell** [scanny/python-pptx#312]
Hello, I'm trying to change the color of a connector ('MSO_CONNECTOR.STRAIGHT). The 'fill' option doesn't seem to work. Any ideas?

**Comment by scanny** [comment]
Have you tried `.line`? The shape is one–dimensional so doesn't have a fill.

**Comment by richielionell** [comment]
I tried this, but I get an error saying - `AttributeError: 'Connector' object has no attribute 'line'`

```
connector = shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Begin_x, Begin_y, End_x, End_y)
color_line = connector.line
color_line.solid()
color_line.fore_color.rgb = RGBColor(0, 0, 0)
```

**Comment by scanny** [comment]
Hmm, interesting, `Connector` does indeed lack a `.line` attribute.

This might get it done in the meantime:

```python
from pptx.dml.line import LineFormat

connector.ln = connector._element.spPr.get_or_add_ln()
line = LineFormat(connector)
```

**Comment by zoeesilcock** [comment]
I tried the code you suggested out:
```
connector = self.shapes.add_connector(
    MSO_CONNECTOR.STRAIGHT, left, top, left, top + height
)
connector.ln = connector._element.spPr.get_or_add_ln()
line = LineFormat(connector)
line.fill.fore_color.rgb = RGBColor(0, 0, 0)
```

But it gave me this error:
```
    File "/my_script.py", line 83, in some_method
      line.fill.fore_color.rgb = RGBColor(0, 0, 0)
    File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/util.py", line 136, in get_prop_value
      value = f(obj)
    File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/dml/line.py", line 72, in fill
      ln = self._get_or_add_ln()
    File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/dml/line.py", line 100, in _get_or_add_ln
      return self._parent.get_or_add_ln()
```

Hopefully this helps with implementing this feature, I ended up going with a rectangle although that isn't a good replacement for connectors in most cases.

**Comment by scanny** [comment]
Your paste of the error is incomplete. What is the exception that is raised? It would be something like `ValueError: something something not found`.

**Comment by zoeesilcock** [comment]
Oh yeah, sorry about that. Here is the exception:
```
AttributeError: 'Connector' object has no attribute 'get_or_add_ln'
```

**Comment by scanny** [comment]
Ah, okay, I think you might need something like this too:

```python
from pptx.shapes.connector import Connector
def patch_connector():
    def get_or_add_ln(self):
        return self._element.spPr.get_or_add_ln()
    Connector.get_or_add_ln = get_or_add_ln
```

You would need to call this `patch_connector()` before the code you pasted in above, so the code would change to this:

```python
from pptx.shapes.connector import Connector

def patch_connector():
    def get_or_add_ln(self):
        return self._element.spPr.get_or_add_ln()
    Connector.get_or_add_ln = get_or_add_ln

patch_connector()

connector = shapes.add_connector(
    MSO_CONNECTOR.STRAIGHT, left, top, left, top + height
)
line = LineFormat(connector.get_or_add_ln())
line.fill.fore_color.rgb = RGBColor(0, 0, 0)
```

Why don't you give that a try and let me know if it works.

**Comment by zoeesilcock** [comment]
I gave it a try and ended up with this new exception:

```
Error: AttributeError: 'CT_LineProperties' object has no attribute 'get_or_add_ln'
...
    File "/my_script.py", line 130, in some_method
      line.fill.fore_color.rgb = RGBColor(0, 0, 0)
    File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/util.py", line 136, in get_prop_value
      value = f(obj)
    File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/dml/line.py", line 72, in fill
      ln = self._get_or_add_ln()
    File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/dml/line.py", line 100, in _get_or_add_ln
      return self._parent.get_or_add_ln()
```

Looks like that `get_or_add_ln` method is needed somewhere else too.

**Comment by scanny** [comment]
Show me the code that's producing that error. `CT_LineProperties` in fact does not get a `ln` child element, so you must have the wrong reference somewhere.

**Comment by zoeesilcock** [comment]
I have just been using the code you mentioned earlier. I don't know which reference could be wrong but here is a fully standalone version of the code which reproduces the issue:
```python
from pptx import Presentation
from pptx.enum.shapes import MSO_CONNECTOR
from pptx.util import Pt
from pptx.dml.color import RGBColor
from pptx.dml.line import LineFormat
from pptx.shapes.connector import Connector

LAYOUT_INDEX = 1
left = Pt(20)
top = Pt(20)
height = Pt(100)

presentation = Presentation('./presentation.pptx')
slide_layout = presentation.slide_layouts[LAYOUT_INDEX]
slide = presentation.slides.add_slide(slide_layout)

# Patch the Connector class
def get_or_add_ln(self):
    return self._element.spPr.get_or_add_ln()
Connector.get_or_add_ln = get_or_add_ln

# Attempt to draw a black line.
connector = slide.shapes.add_connector(
    MSO_CONNECTOR.STRAIGHT, left, top, left, top + height
)
line = LineFormat(connector.get_or_add_ln())
line.fill.fore_color.rgb = RGBColor(0, 0, 0)

presentation.save('./output.pptx')
```

Full output:
```
$ python render_line.py
Traceback (most recent call last):
  File "render_line.py", line 28, in <module>
    line.fill.fore_color.rgb = RGBColor(0, 0, 0)
  File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/util.py", line 136, in get_prop_value
    value = f(obj)
  File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/dml/line.py", line 72, in fill
    ln = self._get_or_add_ln()
  File "/Library/Python/2.7/site-packages/python_pptx-0.6.7-py2.7.egg/pptx/dml/line.py", line 100, in _get_or_add_ln
    return self._parent.get_or_add_ln()
AttributeError: 'CT_LineProperties' object has no attribute 'get_or_add_ln'
```

**Comment by scanny** [comment]
Ah, okay, I see the problem now. `LineFormat()` should take the ("parent") connector object, not its `ln` element. So that line becomes:

```python
line = LineFormat(connector)  # instead of LineFormat(connector.get_or_add_ln())
```

But I think you'll also need to patch in a second item to get all the bits of LineFormat working. It's expecting a `.ln` property on the `Connector` object. You can use an attribute instead:

```python
connector.ln = connector.get_or_add_ln()
```

This will need to appear after you've added the connector of course, since this is patching each instance rather than the class. In this code it would go right before the `line = LineFormat(...)` line.

Why don't you give that a try and see how you go.

**Comment by zoeesilcock** [comment]
That did it, I also needed to add a call to `.solid()` before setting the `fore_color`. Thanks for your help!

Here is the final code for future reference:
```python
from pptx import Presentation
from pptx.enum.shapes import MSO_CONNECTOR
from pptx.util import Pt
from pptx.dml.color import RGBColor
from pptx.dml.line import LineFormat
from pptx.shapes.connector import Connector

LAYOUT_INDEX = 1
left = Pt(20)
top = Pt(20)
height = Pt(100)

presentation = Presentation('./presentation.pptx')
slide_layout = presentation.slide_layouts[LAYOUT_INDEX]
slide = presentation.slides.add_slide(slide_layout)

# Patch the Connector class.
def get_or_add_ln(self):
    return self._element.spPr.get_or_add_ln()
Connector.get_or_add_ln = get_or_add_ln

# Draw a black line.
connector = slide.shapes.add_connector(
    MSO_CONNECTOR.STRAIGHT, left, top, left, top + height
)
connector.ln = connector.get_or_add_ln()
line = LineFormat(connector)
line.fill.solid()
line.fill.fore_color.rgb = RGBColor(0, 0, 0)

presentation.save('./output.pptx')
```

**Comment by scanny** [comment]
Glad you got it working :)

I'll leave this open as a feature request to incorporate this into the `Connector` API.

**Comment by scanny** [comment]
Connector.line was added in release v0.6.12 circa Aug 11 2018.
