### ISSUE TITLE
Error trying out sample examples: AttributeError: 'module' object has no attribute 'SubElement'

### ISSUE THREAD

**Issue by spidezad** [scanny/python-pptx#35]
Hi,

I was trying out the following code on Windows 7( office 2007, python 2.7) when I encounter the issue highlighted

from pptx import Presentation

prs = Presentation()
title_slidelayout = prs.slidelayouts[0]
slide = prs.slides.add_slide(title_slidelayout)
title = slide.shapes.title
subtitle = slide.shapes.placeholders[1]

title.text = "Hello, World!"
subtitle.text = "python-pptx was here!"

Error:
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 323, in RunScript
    debugger.run(codeObject, **main**.**dict**, start_stepping=0)
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\debugger__init__.py", line 60, in run
    _GetCurrentDebugger().run(cmd, globals,locals, start_stepping)
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\debugger\debugger.py", line 655, in run
    exec cmd in globals, locals
  File "C:\Users\356039\Desktop\pythonuserfiles\pptx_try1.py", line 1, in <module>
    from pptx import Presentation
  File "C:\Python27\lib\site-packages\pptx\presentation.py", line 984, in add_slide
    slide = _Slide(slidelayout)
  File "C:\Python27\lib\site-packages\pptx\presentation.py", line 1064, in __init__
    self._element = self.__minimal_element
  File "C:\Python27\lib\site-packages\pptx\presentation.py", line 1098, in __minimal_element
    _SubElement(sld, 'p:cSld', _nsmap)
  File "C:\Python27\lib\site-packages\pptx\oxml.py", line 53, in _SubElement
    return objectify.SubElement(parent, qn(tag), nsmap=nsmap)
AttributeError: 'module' object has no attribute 'SubElement'

May I know what might be causing the error?

Thanks.

**Comment by Uzair919** [comment]
@scanny  i have installed latest version of lxml bu still i receive same error  , when i delete PIL folder from site packages it throws image module not found error , any recommendation to fix 

`import pptx.exc as exceptions
AttributeError: module 'pptx' has no attribute exc`
