### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by lmb22** [scanny/python-pptx#385]
Receive the following error after installing python-pptx and trying to import it:

Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pptx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lburke/anaconda/lib/python2.7/site-packages/pptx/__init__.py", line 13, in <module>
    from pptx.api import Presentation  # noqa
  File "/Users/lburke/anaconda/lib/python2.7/site-packages/pptx/api.py", line 17, in <module>
    from .package import Package
  File "/Users/lburke/anaconda/lib/python2.7/site-packages/pptx/package.py", line 16, in <module>
    from .parts.image import Image, ImagePart
  File "/Users/lburke/anaconda/lib/python2.7/site-packages/pptx/parts/image.py", line 15, in <module>
    import Image as PIL_Image
  File "/Users/lburke/anaconda/lib/python2.7/site-packages/PIL/Image.py", line 27, in <module>
    from . import VERSION, PILLOW_VERSION, _plugins
ValueError: Attempted relative import in non-package
>>>

**Comment by scanny** [comment]
This looks like a problem with your Pillow installation.

When Pillow is correctly installed, this command works from the Python command line:

```python
>>> from PIL import Image
>>>
```

What it would be doing now is something like this:


```python
>>> from PIL import Image
ImportError: ...
```

I expect it has something to do with a preinstalled version or something else with Anaconda package management.
