### ISSUE TITLE
Inserting SVG into picture placeholders 

### ISSUE THREAD

**Issue by jdelight** [scanny/python-pptx#394]
Just wanted to clarify whether inserting SVGs into picture placeholders is supported or if I'm doing something odd. Looks initially to me like it's a limitation of PIL... In which case would there need to be some work on python-pptx to use an image library that supported SVG?

May be related to #383 but I'm not sure it fixes the insert into placeholder issue.

```python
from pptx import Presentation
prs = Presentation('./master.pptx')
slide = prs.slides.add_slide(prs.slide_layouts[0])
ph = slide.placeholders[13]
ph.insert_picture('./image.svg')
prs.save('new.pptx')
```

Error
```python
Traceback (most recent call last):
  File "/pptx-test/lib/python3.6/site-packages/pptx/util.py", line 134, in get_prop_value
    return getattr(obj, cache_attr_name)
AttributeError: 'Image' object has no attribute '_ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pptx-test/lib/python3.6/site-packages/pptx/util.py", line 134, in get_prop_value
    return getattr(obj, cache_attr_name)
AttributeError: 'Image' object has no attribute '__pil_props'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pptx-test/test.py", line 11, in <module>
    ph.insert_picture(file)
  File "/pptx-test/lib/python3.6/site-packages/pptx/shapes/placeholder.py", line 323, in insert_picture
    pic = self._new_placeholder_pic(image_file)
  File "/pptx-test/lib/python3.6/site-packages/pptx/shapes/placeholder.py", line 334, in _new_placeholder_pic
    rId, desc, image_size = self._get_or_add_image(image_file)
  File "/pptx-test/lib/python3.6/site-packages/pptx/shapes/placeholder.py", line 345, in _get_or_add_image
    image_part, rId = self.part.get_or_add_image_part(image_file)
  File "/pptx-test/lib/python3.6/site-packages/pptx/parts/slide.py", line 42, in get_or_add_image_part
    image_part = self._package.get_or_add_image_part(image_file)
  File "/pptx-test/lib/python3.6/site-packages/pptx/package.py", line 50, in get_or_add_image_part
    return self._image_parts.get_or_add_image_part(image_file)
  File "/pptx-test/lib/python3.6/site-packages/pptx/package.py", line 161, in get_or_add_image_part
    image_part = ImagePart.new(self._package, image)
  File "/pptx-test/lib/python3.6/site-packages/pptx/parts/image.py", line 44, in new
    partname = package.next_image_partname(image.ext)
  File "/pptx-test/lib/python3.6/site-packages/pptx/util.py", line 136, in get_prop_value
    value = f(obj)
  File "/pptx-test/lib/python3.6/site-packages/pptx/parts/image.py", line 238, in ext
    format = self._format
  File "/pptx-test/lib/python3.6/site-packages/pptx/parts/image.py", line 273, in _format
    return self._pil_props[0]
  File "/pptx-test/lib/python3.6/site-packages/pptx/util.py", line 136, in get_prop_value
    value = f(obj)
  File "/pptx-test/lib/python3.6/site-packages/pptx/parts/image.py", line 282, in _pil_props
    pil_image = PIL_Image.open(stream)
  File "/pptx-test/lib/python3.6/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x1110a2780>
```

Does anyone have a workaround for inserting SVGs into Powerpoint?

**Comment by scanny** [comment]
The short answer is it isn't supported, and probably won't be until something like PIL supports SVG.

The problem is that an SVG image is stored in PowerPoint as two different formats, so we'd need to convert SVG to PNG, something I've been unable to find support for in a Python library.

PowerPoint didn't support SVG until very recently, and many folks are still running one of those older versions, so an SVG image is inserted with a so-called "fallback", which is basically "here's an SVG, but if you don't understand those, here's a PNG instead".

So a general-case solution would need to insert the SVG, which is probably pretty easy, but also convert the SVG to a PNG and insert that as a fallback, all of which would be hard.

**Comment by jdelight** [comment]
Also is there a workaround in the mean time - for example, is it possible to load a presentation and swap one SVG image for another?

**Comment by jdelight** [comment]
Sounds good - yes using your xml diff tool is where I would have started - as you suggest.

**Comment by goldengrape** [comment]
@jdelight 
Maybe you can try using [Freeform Shapes](https://python-pptx.readthedocs.io/en/latest/dev/analysis/shp-freeform.html) to redraw SVG as an autoshape object. 

@scanny 
Could you please add “Curve segments” part in Freeform Shapes? For svg path, M=moveto, L=lineto, C=curveto, are most useful part, only C=curveto left in python-pptx

**Comment by jdelight** [comment]
Thanks @goldengrape - we'll look into this.

**Comment by aacoimbra** [comment]
@jdelight Do you remember if you managed to fix the low quality .png in the presentation?

**Comment by jdelight** [comment]
@aacoimbra no sorry - might help to play around to sizing but can't remember if we did anything specific.

**Comment by pgiblock** [comment]
`cairosvg`'s `svg2png` works well for me.

**Comment by subhagato** [comment]
@scanny Is it possible to add SVG support without loss of picture quality?

**Comment by PunVas** [comment]
i know i am posting it too late but i have found a workaround. while python-pptx doesn't handle svg but it supports another vector based MIME called [image/x-emf](https://github.com/scanny/python-pptx/blob/master/src/pptx/opc/constants.py#L171) . you can convert the svg to emf and then add that emf to the slides.
this method may lead to quality reduction if complex curves/bezier are present. For best results use inkscape for conversion

**Comment by MartinPacker** [comment]
Maybe not too late...


... my md2pptx (for converting a subset of Markdown to PowerPoint pptx using python-pptx) project can invoke CairoSVG automatically. It creates a bitmap file and embeds that.

Might help you; Might not.

It is at martinpacker/md2pptx on GitHub.
