### ISSUE TITLE
Can't import: ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by mydockergit** [scanny/python-pptx#557]
When I run on Python27 `import pptx` I get the foolowing error:
```
>>> import pptx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\pptx\__init__.py", line 14, in <module>
    from pptx.api import Presentation  # noqa
  File "c:\Python27\lib\site-packages\pptx\api.py", line 15, in <module>
    from .package import Package
  File "c:\Python27\lib\site-packages\pptx\package.py", line 11, in <module>
    from .opc.package import OpcPackage
  File "c:\Python27\lib\site-packages\pptx\opc\package.py", line 13, in <module>
    from .oxml import CT_Relationships, serialize_part_xml
  File "c:\Python27\lib\site-packages\pptx\opc\oxml.py", line 12, in <module>
    from lxml import etree
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

How can I fix it?

**Comment by mydockergit** [comment]
After installing Python 64 it was solved.
