### ISSUE TITLE
Can't open pptx file: zipfile.BadZipfile: Bad CRC-32 for file 'docProps/app.xml'

### ISSUE THREAD

**Issue by mydockergit** [scanny/python-pptx#558]
When I tried to open a Power Point file it failed:  

```
>>> from pptx import Presentation
>>> f = open(r'C:\Users\John\Desktop\myprs.pptx')
>>> prs = Presentation(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\pptx\api.py", line 28, in Presentation
    presentation_part = Package.open(pptx).main_document_part
  File "c:\Python27\lib\site-packages\pptx\opc\package.py", line 125, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "c:\Python27\lib\site-packages\pptx\opc\pkgreader.py", line 37, in from_file
    phys_reader, pkg_srels, content_types
  File "c:\Python27\lib\site-packages\pptx\opc\pkgreader.py", line 70, in _load_serialized_parts
    for partname, blob, srels in part_walker:
  File "c:\Python27\lib\site-packages\pptx\opc\pkgreader.py", line 103, in _walk_phys_parts
    blob = phys_reader.blob_for(partname)
  File "c:\Python27\lib\site-packages\pptx\opc\phys_pkg.py", line 111, in blob_for
    return self._zipf.read(pack_uri.membername)
  File "c:\Python27\lib\zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "c:\Python27\lib\zipfile.py", line 630, in read
    data = self.read1(n)
  File "c:\Python27\lib\zipfile.py", line 692, in read1
    self._update_crc(data, eof=eof)
  File "c:\Python27\lib\zipfile.py", line 647, in _update_crc
    raise BadZipfile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipfile: Bad CRC-32 for file 'docProps/app.xml'
```

**Comment by mydockergit** [comment]
No need to use a file for that. Just run like this:
`prs = Presentation('Test_Pattern.pptx')`
