### ISSUE TITLE
Can't open pptx file: zipfile.BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by mydockergit** [scanny/python-pptx#559]
When I tried to open a Power Point file with this library it failed:
```
>>> from pptx import Presentation
>>> from StringIO import StringIO
>>> with open(r'C:\Users\John\Desktop\myprs.pptx') as f:
...      source = StringIO(f.read())
...
>>> prs = Presentation(source)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\pptx\api.py", line 28, in Presentation
    presentation_part = Package.open(pptx).main_document_part
  File "c:\Python27\lib\site-packages\pptx\opc\package.py", line 125, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "c:\Python27\lib\site-packages\pptx\opc\pkgreader.py", line 33, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "c:\Python27\lib\site-packages\pptx\opc\phys_pkg.py", line 104, in __init__
    self._zipf = ZipFile(pkg_file, "r")
  File "c:\Python27\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "c:\Python27\lib\zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by mydockergit** [comment]
No need to use a file for that. Just run like this:
`prs = Presentation('Test_Pattern.pptx')`
