### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by spudrik95** [scanny/python-pptx#697]
Hi, my code was working. However, since trying a various versions of Python, it is no giving me this error (I have done a fresh install and still doesn't work):

LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "C:/Users/callu/Documents/PythonImport/pythonProject1/pptxLoadImages.py", line 13, in <module>
LogPython: Error:     prs = Presentation('C:/Users/callu/Documents/PythonImport/PythonTest/Script/templatePP')
LogPython: Error:   File "C:/Users/callu/AppData/Local/Programs/Python/Python37/Lib/site-packages\pptx\api.py", line 28, in Presentation
LogPython: Error:     presentation_part = Package.open(pptx).main_document_part
LogPython: Error:   File "C:/Users/callu/AppData/Local/Programs/Python/Python37/Lib/site-packages\pptx\opc\package.py", line 125, in open
LogPython: Error:     pkg_reader = PackageReader.from_file(pkg_file)
LogPython: Error:   File "C:/Users/callu/AppData/Local/Programs/Python/Python37/Lib/site-packages\pptx\opc\pkgreader.py", line 33, in from_file
LogPython: Error:     phys_reader = PhysPkgReader(pkg_file)
LogPython: Error:   File "C:/Users/callu/AppData/Local/Programs/Python/Python37/Lib/site-packages\pptx\opc\phys_pkg.py", line 32, in __new__
LogPython: Error:     raise PackageNotFoundError("Package not found at '%s'" % pkg_file)
LogPython: Error: pptx.exc.PackageNotFoundError: Package not found at 'C:/Users/callu/Documents/PythonImport/PythonTest/Script/templatePP'

**Comment by spudrik95** [comment]
Doesn't matter I am an idiot. Didn't have '.pptx' at my strings
