### ISSUE TITLE
audio objects get mistaken for images

### ISSUE THREAD

**Issue by NathanTech7713** [scanny/python-pptx#734]
Hi, me again.

>>> from pptx import Presentation
>>> prs=Presentation("narrated_powerpoint_presentation.pptx")
>>> slide=prs.slides[1]
>>> shape=slide.shapes[2]
>>> shape.name
'Audio 5'

>>> shape.click_action.action
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python332\lib\site-packages\pptx\action.py", line 53, in action
    return {
KeyError: 'media'

And if you examine the shape it acts like it is an image file rather than audio.
Preferred solutions/workarounds:
1. To be able to recognise that it is audio.
2. 2. To be able to retrieve the name of the media file which I can then extract from the pptx as a zip.
[Uploading narrated_powerpoint_presentation.pptx…]()

**Comment by scanny** [comment]
Okay, this one looks like another implementation boundary, although it's unfortunate that it can produce an exception. Minimally it would be better if it returned `PP_ACTION.NONE` rather than raising `KeyError`. I'll see if I can get that fixed up in the release that's currently open and should go out by the end of the month.

The image-like behavior is expected I believe. You haven't mentioned specifically in what ways it acts like one, but there is no "sound" shape and what you would typically expect is a picture of an "audio speaker" icon, which is of course an image. So I'm not sure there is anything out of the ordinary there. The `shape.shape_type` property will report `MSO.PICTURE`, but that's because there is no distinct `Audio` object yet.

As far as being able to detect that it has "linked" sound, that's a legitimate feature request so I've changed the title to reflect that and we'll leave this open as a feature request. I expect audio would be detected something like this:

```python
has_audio = shape.shape_type == MSO_SHAPE_TYPE.MEDIA and shape.media_type == PP_MEDIA_TYPE.SOUND
```

**Comment by NathanTech7713** [comment]
@scanny thanks for that. do you know is there a way (current or otherwise), to draw out which file the audio shape is pointing to in the pptx, i.E, which media.mp3 file is associated?

**Comment by scanny** [comment]
Do a `print(shape._sp.xml)` on the shape you know has one and let's have a look. Pretty sure that would be doable.

**Comment by NathanTech7713** [comment]
Heya.
So shape._sp.xml said not found but shape.element.xml worked, assuming that's basically the same thing.
I've included the output below, I assume the either the rId="2" or id="6" points to the media in the format of file="media"+str(id) but I am probably wrong here.

>>> shape.element.xml
'<p:pic xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.ope
nxmlformats.org/officeDocument/2006/relationships">\n  <p:nvPicPr>\n    <p:cNvPr id="6" name="Audio 5">\n      <a:hlinkClick r:id="" action="ppaction://media"/>\n    </
p:cNvPr>\n    <p:cNvPicPr>\n      <a:picLocks noChangeAspect="1"/>\n    </p:cNvPicPr>\n    <p:nvPr>\n      <a:audioFile r:link="rId2"/>\n      <p:extLst>\n        <p:ex
t uri="{DAA4B4D4-6D71-4841-9C94-3DE7FCFB9230}">\n          <p14:media xmlns:p14="http://schemas.microsoft.com/office/powerpoint/2010/main" r:embed="rId1"/>\n        </p
:ext>\n      </p:extLst>\n    </p:nvPr>\n  </p:nvPicPr>\n  <p:blipFill>\n    <a:blip r:embed="rId4"/>\n    <a:stretch>\n      <a:fillRect/>\n    </a:stretch>\n  </p:bli
pFill>\n  <p:spPr>\n    <a:xfrm>\n      <a:off x="8382000" y="6096000"/>\n      <a:ext cx="609600" cy="609600"/>\n    </a:xfrm>\n    <a:prstGeom prst="rect">\n      <a:
avLst/>\n    </a:prstGeom>\n  </p:spPr>\n</p:pic>\n'

**Comment by NathanTech7713** [comment]
Morning @scanny was just doing a little research and stumbled across a stackoverflow question regarding image file names and how power point seems to embed the original file name as alternative text/image descriptions. Is that what we see through shape.image.filename? If not is there a way to pull this out as if that points to media1.wav for instance, then problem solved for me

**Comment by NathanTech7713** [comment]
Forgot to include the link, it's in the second answer, not the first.
https://graphicdesign.stackexchange.com/questions/48906/how-to-find-name-of-original-image-in-powerpoint-presentation

**Comment by scanny** [comment]
@NathanTech7713 I reformatted the XML you provided so it was readable, please take care of that yourself next time.

You'll need to do a little investigation yourself on this, but the audio is either going to be on `"rId1"` or `"rId2"`. The `id="6"` is the shape-id and does not correspond to a relationship to another package part.

I'm not sure why there would be 2 relationships but the next step would be to inspect the `slide2.xml.rels` file and see what these relationships point to. Then you can have a look at those files in the package if necessary. It could be they are two "links" to the same resource or it could be that one is a legacy format and the other a new format of the same audio.

As far as detecting these shapes is concerned you could narrow it to shapes that reported picture type, like `shape.shape_type == MSO.PICTURE`. From there you could use XPath, maybe to look for the `p:nvPr/a:audioFile` element:

```python
def has_audio(shape):
    """Return True if `shape` has embedded audio, False otherwise."""
    if shape.shape_type != MSO.PICTURE:
        return False
    audioFiles = shape._pic.xpath(".//p:nvPr/a:audioFile")
    return True if audioFiles else False
```

Actually, after writing this I notice that the `a:audioFile` element has an `r:link` attribute and the `p14:media` element has an `r:embed` attribute. This might mean that the latter is a "link" to an embedded sound file and the former is a URL to a sound resource on the web or something.

**Comment by NathanTech7713** [comment]
@scanny Thanks for that. My sincere apologies. A byproduct of rarely working with others leaves me a bit ignorant of how best to format for other's reading sometimes :) we live and learn!

Anyways, I took a gander at the .rels file you mentioned and sure enough, plain as brass, there it is. Studying this file it looks like one rId points to a 2006 link, while the rId3 points to a 2007 link.

thanks for the code above, as well. I need to sit down si down and play with it and this a bit to see where I get, but if I get somewhere is it worth doing a PR?

**Comment by scanny** [comment]
It might be worth developing a PR, especially if you will be patching your own fork, but be aware it would be very unlikely to get merged into the library. Short version of that is it's unlikely to have all the analysis documentation, tests, and consistency with implementation conventions and standards. It just generally works out that it's faster to reimplement something from scratch than incorporate a contributed PR. Generally we don't implement anything new unless it's sponsored and we have the nights and weekend time to get to it (which hasn't been the case lately).

But that doesn't mean it wouldn't be used to inform such a feature if it was added or for someone else to pick up and merge into their own fork. You just have to decide whether it's worth it to you if it won't get merged.

**Comment by MartinPacker** [comment]
Just a thought:

We could use a repository of companion samples. I don't think StackOverflow is it - nor is the GitHub Issues capability.

While I can't own such a thing I'd (for what it's worth) contribute to it.

**Comment by scanny** [comment]
`KeyError` behavior on a media click-action (click "audio/speaker" icon to play MP3) is replaced by returning `PP_ACTION.NONE` in the upcoming release `0.6.20` that should be out later today or tomorrow.
