### ISSUE TITLE
can't import module

### ISSUE THREAD

**Issue by KonradowyPL** [scanny/python-pptx#820]
while importing module this error message shown:

Traceback (most recent call last):
  File "...\Python\Python310\lib\site-packages\pptx\compat\__init__.py", line 10, in <module>
    Container = collections.abc.Container
AttributeError: module 'collections' has no attribute 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\main.py", line 1, in <module>
  File "...\Python\Python310\lib\site-packages\pptx\__init__.py", line 14, in <module>
    from pptx.api import Presentation  # noqa
  File "...\Python\Python310\lib\site-packages\pptx\api.py", line 15, in <module>
  File "...\Python\Python310\lib\site-packages\pptx\package.py", line 6, in <module>
    from pptx.opc.package import OpcPackage
  File "...\Python\Python310\lib\site-packages\pptx\opc\package.py", line 11, in <module>
  File "...\Python\Python310\lib\site-packages\pptx\compat\__init__.py", line 14, in <module>
    Container = collections.Container
AttributeError: module 'collections' has no attribute 'Container'

**Comment by SoloJoeKing** [comment]
I was able to get it to work by adding - 'import collections.abc' in __init__.py file.  
[File "...\Python\Python310\lib\site-packages\pptx_init_.py", line 14] -

**Comment by AJHutchenreuther** [comment]
**SoloJoeKing**  _
> _I was able to get it to work by adding - 'import collections.abc' in **init**.py file. [File "...\Python\Python310\lib\site-packages\pptx_init_.py", line 14]__ 
- Thank you.  Same error message for your comment gave me enough information to make it work.  I edited at this location:
[File "...\AppData\Local\Programs\Python\Python310\Lib\site-packages\pptx\compat\__init__.py"]
I added:
_import_ _collections.abc_ immediately below _import collections_.
Particulars:  Novice in Visual Studio Code in Windows 11, Python 3.10.

**Comment by kascodeo** [comment]
This issue is fixed. [python-pptx-fix](https://pypi.org/project/python-pptx-fix/)

**Comment by scanny** [comment]
Fixed in release 0.6.22 circa Aug 28, 2023.
