### ISSUE TITLE
Python pptx running with python 3.9 but not on 3.10

### ISSUE THREAD

**Issue by ShreyanshKhale** [scanny/python-pptx#878]
### Getting error in import-
**from pptx import Presentation shows error in python 3.10 as**

Traceback (most recent call last):
  File "C:\Users\kshreyan\AppData\Local\Programs\Python\Python310\lib\site-packages\pptx\compat\__init__.py", line 10, in <module>
    Container = collections.abc.Container
AttributeError: module 'collections' has no attribute 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\kshreyan\xxx\test.py", line 2, in <module>
    from pptx import Presentation
  File "C:\Users\kshreyan\AppData\Local\Programs\Python\Python310\lib\site-packages\pptx\__init__.py", line 14, in <module>
    from pptx.api import Presentation  # noqa
  File "C:\Users\kshreyan\AppData\Local\Programs\Python\Python310\lib\site-packages\pptx\api.py", line 15, in <module>
    from .package import Package
  File "C:\Users\kshreyan\AppData\Local\Programs\Python\Python310\lib\site-packages\pptx\package.py", line 6, in <module>
    from pptx.opc.package import OpcPackage
  File "C:\Users\kshreyan\AppData\Local\Programs\Python\Python310\lib\site-packages\pptx\opc\package.py", line 11, in <module>
    from pptx.compat import is_string, Mapping
  File "C:\Users\kshreyan\AppData\Local\Programs\Python\Python310\lib\site-packages\pptx\compat\__init__.py", line 14, in <module>     
    Container = collections.Container
AttributeError: module 'collections' has no attribute 'Container'

**Comment by sedrew** [comment]
I created  [petpptx](https://github.com/sedrew/petpptx) a fork of this project, and I support it, I often use it in my work. I also added a setter for Run.font. Now you can copy styles.

**Comment by kascodeo** [comment]
This issue is fixed. [python-pptx-fix](https://pypi.org/project/python-pptx-fix/)

**Comment by scanny** [comment]
Fixed in release 0.6.22 circa Aug 28, 2023.
